version: '3.1'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: p1_woedpress
    restart: always
    volumes:
      - ./www/:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: db_p4ssw0rd!
      
    ports:
      - 8080:80
    networks:
      - p1_network
  db:
    image: mariadb:latest
    container_name: p1_mariadb
    restart: always
    volumes:
       - p1_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_wordpress
      MYSQL_ROOT_PASSWORD: db_p4ssw0rd!
    networks:
      - p1_network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: p1_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: db_p4ssw0rd!
    networks:
      - p1_network
networks:
  p1_network:
volumes:
  p1_data:
